### ISSUE TITLE
集合型を書き込む時にnullを設定するとNullPointerExceptionが発生する。

### ISSUE THREAD

**Issue by mygreen** [mygreen/xlsmapper#41]
Set（集合）を書き込む場合、NullPointerExceptionが発生する。

``` java
java.lang.IllegalArgumentException: targetClass should not be null.
	at com.gh.mygreen.xlsmapper.ArgUtils.notNull(ArgUtils.java:23)
	at com.gh.mygreen.xlsmapper.Utils.convertToObject(Utils.java:1719)
	at com.gh.mygreen.xlsmapper.cellconvert.converter.ListCellConverter.convertList(ListCellConverter.java:72)
	at com.gh.mygreen.xlsmapper.cellconvert.converter.SetCellConverter.toCell(SetCellConverter.java:93)
	at com.gh.mygreen.xlsmapper.cellconvert.converter.SetCellConverter.toCell(SetCellConverter.java:52)
	at com.gh.mygreen.xlsmapper.fieldprocessor.processor.HorizontalRecordsProcessor.saveRecords(HorizontalRecordsProcessor.java:695)
	at com.gh.mygreen.xlsmapper.fieldprocessor.processor.HorizontalRecordsProcessor.saveProcess(HorizontalRecordsProcessor.java:468)
	at com.gh.mygreen.xlsmapper.fieldprocessor.processor.HorizontalRecordsProcessor.saveProcess(HorizontalRecordsProcessor.java:1)
	at com.gh.mygreen.xlsmapper.FieldAdaptorProxy.saveProcess(FieldAdaptorProxy.java:65)
	at com.gh.mygreen.xlsmapper.XlsSaver.saveSheet(XlsSaver.java:282)
	at com.gh.mygreen.xlsmapper.XlsSaver.save(XlsSaver.java:114)
	at com.gh.mygreen.xlsmapper.XlsSaver.save(XlsSaver.java:67)
	at com.gh.mygreen.xlsmapper.XlsMapper.save(XlsMapper.java:191)
	at com.gh.mygreen.xlsmapper.cellconvert.CollectionCellConveterTest.test_save_collection(CollectionCellConveterTest.java:262)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

**Comment by mygreen** [comment]
fix v0.5

- Set（集合）の時に、Genericsタイプを取得する処理が間違っていた。ifの条件文として、Set.classに対する処理がなかった。
- 他のList、Arrayは問題なし。
